services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  integrations:
    image: integrations
    build:
      context: .
      dockerfile: Integrations/Dockerfile
